import type { Metadata } from "next";
import { COMPANY_ADDRESS, COMPANY_LEGAL_NAME, PORTAL_URL } from "@/lib/legal";
import {
  LegalArticle,
  LegalContactSection,
} from "../_components/legal-article";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy Policy of the IPA Portal — how Ideal Play Abacus India Pvt. Ltd. collects, uses and protects personal information on its franchise-management service.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalArticle title="Privacy Policy">
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law
        protects You.
      </p>
      <p>
        We use Your Personal Data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <section>
        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li>
            <strong>&ldquo;Account&rdquo;</strong> means a unique account
            created for You to access our Service or parts of our Service.
          </li>
          <li>
            <strong>&ldquo;Company&rdquo;</strong> (referred to as either
            &ldquo;the Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or
            &ldquo;Our&rdquo; in this Agreement) refers to {COMPANY_LEGAL_NAME}
            , {COMPANY_ADDRESS}.
          </li>
          <li>
            <strong>&ldquo;Cookies&rdquo;</strong> are small files that are
            placed on Your computer, mobile device or any other device by a
            website, containing the details of Your browsing history on that
            website among its many uses.
          </li>
          <li>
            <strong>&ldquo;Country&rdquo;</strong> refers to: India, and in
            specific, the State of Tamil Nadu.
          </li>
          <li>
            <strong>&ldquo;Device&rdquo;</strong> means any device that can
            access the Service such as a computer, a cellphone or a digital
            tablet.
          </li>
          <li>
            <strong>&ldquo;Personal Data&rdquo;</strong> is any information
            that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>&ldquo;Service&rdquo;</strong> refers to the Website.
          </li>
          <li>
            <strong>&ldquo;Service Provider&rdquo;</strong> means any natural
            or legal person who processes the data on behalf of the Company.
            It refers to third-party companies or individuals employed by the
            Company to facilitate the Service, to provide the Service on
            behalf of the Company, to perform services related to the Service
            or to assist the Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>&ldquo;Usage Data&rdquo;</strong> refers to data collected
            automatically, either generated by the use of the Service or from
            the Service infrastructure itself (for example, the duration of a
            page visit).
          </li>
          <li>
            <strong>&ldquo;Website&rdquo;</strong> refers to the IPA Portal,
            accessible from <a href={PORTAL_URL}>{PORTAL_URL}</a>
          </li>
          <li>
            <strong>&ldquo;You&rdquo;</strong> means the individual accessing
            or using the Service, or the company, or other legal entity on
            behalf of which such individual is accessing or using the Service,
            as applicable.
          </li>
        </ul>
      </section>

      <section>
        <h2>Collecting and Using Your Personal Data</h2>
        <h3>Personal Data</h3>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but
          is not limited to:
        </p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>
            Photographs and signatures submitted for identification and for
            the execution of agreements
          </li>
          <li>
            Educational and business details submitted in franchise or course
            instructor applications
          </li>
          <li>Usage Data</li>
        </ul>
        <h3>Student Information</h3>
        <p>
          Franchisees and course instructors may enter information about
          students enrolled at their centres — such as a student&apos;s name,
          date of birth, guardian contact details, enrolment details and
          progress records — in order to manage training, assessments,
          certificates and ID cards. This information is collected and used
          solely to provide the Service. Each centre is responsible for
          obtaining the necessary consent from a student&apos;s parent or
          guardian before entering this information on the Service.
        </p>
        <h3>Usage Data</h3>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as Your Device&apos;s
          Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that You visit, the time and date
          of Your visit, the time spent on those pages, unique device
          identifiers and other diagnostic data.
        </p>
        <h3>Cookies</h3>
        <p>
          We use essential Cookies to operate the Service — in particular,
          session Cookies that keep You signed in and protect Your account. We
          do not use Cookies for advertising or cross-site tracking. You can
          instruct Your browser to refuse all Cookies or to indicate when a
          Cookie is being sent; however, if You do not accept Cookies, You
          will not be able to sign in to the Service.
        </p>
      </section>

      <section>
        <h2>Use of Your Personal Data</h2>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li>
            <strong>To provide and maintain our Service</strong>, including to
            monitor the usage of our Service.
          </li>
          <li>
            <strong>To manage Your Account:</strong> to manage Your
            registration as a user of the Service. The Personal Data You
            provide can give You access to different functionalities of the
            Service that are available to You as a registered user.
          </li>
          <li>
            <strong>For the performance of a contract:</strong> the
            development, compliance and undertaking of the purchase contract
            for the products, items or services You have purchased, of Your
            franchise or training agreement, or of any other contract with Us
            through the Service.
          </li>
          <li>
            <strong>To contact You:</strong> to contact You by email,
            telephone calls or SMS regarding updates or informative
            communications related to the functionalities, products or
            contracted services, including order confirmations, payment
            receipts, agreement renewals, certificate dispatches and expiry
            reminders.
          </li>
          <li>
            <strong>To manage Your requests:</strong> to attend and manage
            Your requests to Us.
          </li>
          <li>
            <strong>For business transfers:</strong> We may use Your
            information to evaluate or conduct a merger, divestiture,
            restructuring, reorganization, dissolution, or other sale or
            transfer of some or all of Our assets, in which Personal Data held
            by Us about our Service users is among the assets transferred.
          </li>
          <li>
            <strong>For other purposes:</strong> We may use Your information
            for other purposes, such as data analysis, identifying usage
            trends and evaluating and improving our Service, products and
            services.
          </li>
        </ul>
      </section>

      <section>
        <h2>Payment Information</h2>
        <p>
          Payments made through the Service are processed by Razorpay, a
          third-party payment gateway. We do not collect or store Your card
          numbers, UPI credentials or banking passwords; that information is
          provided by You directly to Razorpay and its handling is governed by
          Razorpay&apos;s privacy policy, available at{" "}
          <a href="https://razorpay.com/privacy/">
            https://razorpay.com/privacy/
          </a>
          . We receive and retain only the confirmation of a payment, such as
          the payment reference, amount, method and status.
        </p>
      </section>

      <section>
        <h2>Retention of Your Personal Data</h2>
        <p>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to
          retain your data to comply with applicable laws), resolve disputes,
          and enforce our legal agreements and policies.
        </p>
        <p>
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally
          obligated to retain this data for longer time periods.
        </p>
      </section>

      <section>
        <h2>Disclosure of Your Personal Data</h2>
        <h3>Business Transactions</h3>
        <p>
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>
        <h3>Law Enforcement</h3>
        <p>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to
          valid requests by public authorities (e.g. a court or a government
          agency).
        </p>
        <h3>Other Legal Requirements</h3>
        <p>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>
            Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            Protect the personal safety of users of the Service or the public
          </li>
          <li>Protect against legal liability</li>
        </ul>
      </section>

      <section>
        <h2>Security of Your Personal Data</h2>
        <p>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use
          commercially acceptable means to protect Your Personal Data, We
          cannot guarantee its absolute security.
        </p>
      </section>

      <section>
        <h2>Children&apos;s Privacy</h2>
        <p>
          The Service is not offered to anyone under the age of 18, and We do
          not knowingly allow anyone under 18 to hold an account. Information
          about students under 18 is entered on the Service by franchisees and
          course instructors only for the purpose of managing those
          students&apos; enrolment and training, as described under
          &ldquo;Student Information&rdquo; above. If You are a parent or
          guardian and You are aware that information about Your child has
          been provided to Us without Your consent, please contact Us and We
          will take steps to remove that information from Our servers.
        </p>
      </section>

      <section>
        <h2>Links to Other Websites</h2>
        <p>
          Our Service may contain links to other websites that are not
          operated by Us. If You click on a third party link, You will be
          directed to that third party&apos;s site. We strongly advise You to
          review the Privacy Policy of every site You visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the
          content, privacy policies or practices of any third party sites or
          services.
        </p>
      </section>

      <section>
        <h2>Changes to this Privacy Policy</h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify
          You of any changes by posting the new Privacy Policy on this page
          and updating the &ldquo;Last updated&rdquo; date at the top of this
          Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
      </section>

      <LegalContactSection intro="If you have any questions about this Privacy Policy, You can contact us:" />
    </LegalArticle>
  );
}
